"""
STEP 6 — Write the split
Creates train.txt, val.txt, test.txt, data_grouped_v1.yaml, assignments.csv (verify).
"""
import os
import sys
import csv
import yaml

DATASET_ROOT = "C:/Users/luise/OneDrive/Documentos/DECAFIA_v2/01_dataset/decafia_clean"
SPLIT_DIR = os.path.join(DATASET_ROOT, "split_grouped_v1")
AUDIT_DIR = "C:/Users/luise/temp/decafia-research/audits/near_duplicates"
ASSIGNMENTS_CSV = os.path.join(SPLIT_DIR, "assignments.csv")
ORIGINAL_YAML = os.path.join(DATASET_ROOT, "data.yaml")

os.makedirs(SPLIT_DIR, exist_ok=True)

def load_assignments():
    with open(ASSIGNMENTS_CSV, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))

def get_image_path(stem, split):
    for ext in ['.jpg', '.jpeg', '.png', '.bmp']:
        p = os.path.join(DATASET_ROOT, "images", split, stem + ext)
        if os.path.exists(p):
            return p
    return None

def main():
    print("=== STEP 6: WRITE SPLIT ===")

    assignments = load_assignments()
    print(f"Loaded {len(assignments)} assignment rows")

    # 1. Read original data.yaml
    with open(ORIGINAL_YAML, 'r', encoding='utf-8') as f:
        orig_yaml = yaml.safe_load(f)

    nc = orig_yaml.get('nc')
    names = orig_yaml.get('names')
    print(f"Original data.yaml: nc={nc}, names={names}")

    if nc != 3:
        raise ValueError(f"STOP: expected nc=3, got nc={nc}")
    if isinstance(names, dict):
        names_list = [names[i] for i in sorted(names.keys())]
    elif isinstance(names, list):
        names_list = names
    else:
        raise ValueError(f"Unexpected names type: {type(names)}")

    if names_list != ['roya', 'coco', 'minador']:
        raise ValueError(f"STOP: expected names=[roya,coco,minador], got {names_list}")
    print(f"Verified: nc=3, names={names_list}")

    # 2. Build path lists per new split
    # Resolve image paths from old_split (that's where the images actually are)
    split_paths = {'train': [], 'val': [], 'test': []}
    missing_images = []

    for row in assignments:
        stem = row['stem']
        old_split = row['old_split']
        new_split = row['new_split']

        img_path = get_image_path(stem, old_split)
        if img_path is None:
            missing_images.append(f"{stem} (old_split={old_split})")
            continue

        # Convert to forward-slash absolute path
        img_path_fwd = img_path.replace('\\', '/')
        split_paths[new_split].append(img_path_fwd)

    if missing_images:
        print(f"ERROR: {len(missing_images)} missing images:")
        for m in missing_images[:10]:
            print(f"  {m}")
        raise FileNotFoundError(f"Missing {len(missing_images)} images")

    # Sort each list
    for s in ['train', 'val', 'test']:
        split_paths[s].sort()

    counts = {s: len(split_paths[s]) for s in ['train', 'val', 'test']}
    total = sum(counts.values())
    print(f"\nSplit counts: train={counts['train']}, val={counts['val']}, test={counts['test']}, total={total}")

    if total != 2315:
        raise ValueError(f"STOP: total={total} != 2315")

    # 3. Write train.txt, val.txt, test.txt
    for split_name in ['train', 'val', 'test']:
        txt_path = os.path.join(SPLIT_DIR, f"{split_name}.txt")
        with open(txt_path, 'w', encoding='utf-8') as f:
            for p in split_paths[split_name]:
                f.write(p + '\n')
        print(f"Wrote {txt_path}: {len(split_paths[split_name])} paths")

    # 4. Write data_grouped_v1.yaml
    data_yaml_path = os.path.join(SPLIT_DIR, "data_grouped_v1.yaml")
    split_dir_fwd = SPLIT_DIR.replace('\\', '/')
    dataset_root_fwd = DATASET_ROOT.replace('\\', '/')

    yaml_content = f"""# DECAFIA grouped split v1 — leakage-safe grouped split
# Generated by split_grouped_v1 pipeline
# Method: prefix+block grouping B=20, randomized assignment

path: {dataset_root_fwd}
train: {split_dir_fwd}/train.txt
val: {split_dir_fwd}/val.txt
test: {split_dir_fwd}/test.txt

nc: 3
names: [roya, coco, minador]
"""
    with open(data_yaml_path, 'w', encoding='utf-8') as f:
        f.write(yaml_content)
    print(f"Wrote {data_yaml_path}")

    # 5. Verify assignments.csv already exists (from Step 4+5)
    print(f"\nVerifying assignments.csv: {len(assignments)} rows")
    required_fields = ["stem", "old_split", "new_split", "group_id", "prefix",
                       "source", "roya_count", "coco_count", "minador_count", "is_background"]
    if assignments:
        actual_fields = list(assignments[0].keys())
        for f in required_fields:
            if f not in actual_fields:
                raise ValueError(f"Missing field '{f}' in assignments.csv")
    print("assignments.csv fields: OK")

    # Report balance
    from collections import Counter
    new_split_counts = Counter(r['new_split'] for r in assignments)
    total_roya = sum(int(r['roya_count']) for r in assignments)
    total_coco = sum(int(r['coco_count']) for r in assignments)
    total_minador = sum(int(r['minador_count']) for r in assignments)
    total_bg = sum(1 for r in assignments if r['is_background'].lower() == 'true')

    print(f"\n--- Balance table (new split) ---")
    print(f"{'Split':<8} {'Images':>7} {'Roya%':>7} {'Coco%':>7} {'Min%':>7} {'Bg%':>7}")
    for split_name in ['train', 'val', 'test']:
        rows_s = [r for r in assignments if r['new_split'] == split_name]
        n = len(rows_s)
        r_pct = sum(int(r['roya_count']) for r in rows_s) / total_roya * 100 if total_roya else 0
        c_pct = sum(int(r['coco_count']) for r in rows_s) / total_coco * 100 if total_coco else 0
        m_pct = sum(int(r['minador_count']) for r in rows_s) / total_minador * 100 if total_minador else 0
        b_pct = sum(1 for r in rows_s if r['is_background'].lower() == 'true') / total_bg * 100 if total_bg else 0
        print(f"{split_name:<8} {n:>7} {r_pct:>7.1f} {c_pct:>7.1f} {m_pct:>7.1f} {b_pct:>7.1f}")

    print(f"\nStep 6 complete.")

if __name__ == "__main__":
    main()
